### ISSUE TITLE
error when running server

### ISSUE THREAD

**Issue by kra** [breedx2/noshare#3]
I may be running an improper docker, see issue #2 
I followed README-server.md
I did not perform any optional steps
I created a keys directory but did not put any user keys in it after discussion with developer

karl@tehom:~/Documents/noshare-server$ ./server.sh
/home/karl/Documents/noshare-server
Defaulting to incoming port 20666
Defaulting keys dir to /home/karl/Documents/noshare-server/keys
NOSHARE_HOST_KEYS_DIR not specified and default not found
New host keys will be generated on container start.
* Users may need to update their server fingerprint!
docker: invalid reference format.
See 'docker run --help'.

karl@tehom:~/Documents/noshare-server$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4

**Comment by breedx2** [comment]
@kra can you put an `echo` in front of the `docker run` in `server.sh` on line 48 and paste the output here?

**Comment by breedx2** [comment]
in any case, you shouldn't strictly have to generate hostkeys, but if you don't create a keys dir for user pubkeys they nobody will be able to access your server.

**Comment by breedx2** [comment]
@kra is this still an issue or did the fix to #2 also resolve this one?

**Comment by breedx2** [comment]
reopen if still relevant.
