### ISSUE TITLE
`noshare <id>` output cascades upward, fills the terminal

### ISSUE THREAD

**Issue by zkarcher** [breedx2/noshare#8]
## Setup

Computer: 2018 Razer Blade 17"
OS: Ubuntu 22.04, default window manager
Terminal: rxvt-unicode aka "urxvt": http://software.schmorp.de/pkg/rxvt-unicode.html

## Steps to reproduce

1). Open a urxvt terminal.
2). Run `noshare <id>` using a file's share id.

## Expected result

Spiffy progress bar ASCII animation, attached to the bottom of the terminal window.

## Actual result

Progress bar updates cascade upward, covering the terminal. Please see attached screenshot (some of the text is redacted)

![noshare_terminal_urxvt](https://user-images.githubusercontent.com/177089/224910507-755dfe5a-ecca-47e2-88c2-aca3db79ab16.png)

**Comment by breedx2** [comment]
Another user claims to have this same issue in `screen`. That could be a nice way to test.
